#!/bin/sh -e

date=$(date +%Y%m%d)a
date2=$(date +%d/%m/%Y)
date3=$(date '+%a, %d %h %Y')
index=$(printf %d '"a')

while [ -f "$date" ]; do
    index=$((index + 1))
    date=${date%%?}$(printf %b "$(printf \\x%x "$index")")
done

cat > "$date.txt" <<EOF
---
title: "$date2: $1"
---
EOF

rss="<item>
<title>$date2: $1</title>
<description></description>
<link>https://dilyn-corner.github.io/papers/$date</link>
<guid isPermaLink=\"true\">https://dilyn-corner.github.io/papers/$date/</guid>
<pubDate>$date3 00:00:00 +0000</pubDate>
</item>"

entry="- <a href=/papers/$date>$date2: $1</a>"

while read -r line; do
    printf '%s\n' "$line"

    case $line in *'<atom'*) printf '%s\n' "$rss"; esac
done < papers.xml > papers.xml.new

mv -f papers.xml.new papers.xml

while read -r line; do
    [ "$yup" ] || case $line in -*) printf '%s\n' "$entry"; yup=1; esac

    printf '%s\n' "$line"
done < ../papers.txt > ../papers.txt.new

mv -f ../papers.txt.new ../papers.txt
